// Load data from data.json (generated by fetch_data.py using yfinance)

const loading = document.getElementById('loading');
const stockBody = document.getElementById('stockBody');

async function loadData() {
    try {
        const response = await fetch('data.json');
        const results = await response.json();
        results.sort((a, b) => b.momentum - a.momentum);
        stockBody.innerHTML = '';
        results.forEach((stock, index) => {
            const row = document.createElement('tr');
            row.innerHTML = `
                <td>${index + 1}</td>
                <td>${stock.symbol}</td>
                <td>${stock.name}</td>
                <td>${stock.momentum.toFixed(2)}%</td>
                <td>$${stock.currentPrice.toFixed(2)}</td>
            `;
            stockBody.appendChild(row);
        });
        loading.style.display = 'none';
    } catch (error) {
        console.error('Error loading data:', error);
        alert('Fetch error: ' + error.message);  // Temporary alert for debugging
        stockBody.innerHTML = '<tr><td colspan="5">Error loading data. Run fetch_data.py first.</td></tr>';
        loading.style.display = 'none';
    }
}

loadData();
